-- AlterTable
ALTER TABLE "TokenSnapshot" ALTER COLUMN "ageMinutes" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserFilter" ALTER COLUMN "minTokenAgeMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maxTokenAgeMinutes" SET DATA TYPE DOUBLE PRECISION;
